EMAIL_MAX_LENGTH = 254
NAME_MAX_LENGTH = 256
SLUG_MAX_LENGTH = 50
USERNAME_MAX_LENGTH = 150
DESCRIPTION_LENGTH = 50
MIN_SCORE = 1
MAX_SCORE = 10
SCORE_ERROR_MESSAGE = (
    f'Оценка должна быть в диапазоне от {MIN_SCORE} до {MAX_SCORE}.')
