# Generated by Django 3.2 on 2024-11-08 08:35

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[api.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
