# Generated by Django 3.2 on 2024-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(max_length=256, null=True, verbose_name='Описание произведения'),
        ),
    ]
