# Generated by Django 3.2 on 2024-11-10 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text=('Укажите пользователя.',), max_length=150, unique=True, validators=[reviews.validators.validate_username], verbose_name='Никнейм'),
        ),
    ]
