# Generated by Django 3.2 on 2024-11-09 13:17

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text=('Укажите пользователя.',), max_length=150, unique=True, validators=[reviews.validators.validate_username], verbose_name='Пользователь'),
        ),
    ]
