# Generated by Django 3.2 on 2024-11-10 09:45

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20241110_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text=('Укажите пользователя.',), max_length=150, unique=True, validators=[reviews.validators.validate_username], verbose_name='Псевдоним'),
        ),
    ]
